version: '3.8'

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/data/postgresql
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

volumes:
  data:
    driver: local